export const productList = [
  { id: 1, img: "/img/p15.png", description: "Product Name" },
  { id: 2, img: "/img/p1.png", description: "Product Name" },
  { id: 3, img: "/img/p2.png", description: "Product Name" },
  { id: 4, img: "/img/p3.png", description: "Product Name" },
  { id: 5, img: "/img/p4.png", description: "Product Name" },
  { id: 6, img: "/img/p5.png", description: "Product Name" },
  { id: 7, img: "/img/p6.png", description: "Product Name" },
  { id: 8, img: "/img/p7.png", description: "Product Name" },
  { id: 9, img: "/img/p8.png", description: "Product Name" },
  { id: 10, img: "/img/p9.png", description: "Product Name" },
  { id: 11, img: "/img/p10.png", description: "Product Name" },
  { id: 12, img: "/img/p11.png", description: "Product Name" },
  { id: 13, img: "/img/p12.png", description: "Product Name" },
  { id: 14, img: "/img/p13.png", description: "Product Name" },
  { id: 15, img: "/img/p14.png", description: "Product Name" },
  { id: 16, img: "/img/p15.png", description: "Product Name" },
  { id: 17, img: "/img/p16.png", description: "Product Name" },
  { id: 18, img: "/img/p17.png", description: "Product Name" },
];
